---

# rule mode

####################
### 自定义设置 ######
####################
my_setting:
- &time_test 300  # 节点延迟测试的间隔（秒）
- &time_update 28800  # 节点订阅更新的间隔（秒）
- &time_update_rule 28800  # 规则更新的间隔（秒）
- &test_url "http://www.gstatic.com/generate_204"  # 延迟测试链接 # http://www.gstatic.com/generate_204 或 https://cp.cloudflare.com


#################################################################################
### head from https://github.com/lhie1/Rules/blob/master/Clash/Head_dns.yaml ####
#################################################################################

mixed-port: 2333
# port: 7890  # http代理
# socks-port: 7891  # socks代理
# redir-port: 7892  # Linux会用到
allow-lan: true
mode: Script
log-level: info
external-controller: 127.0.0.1:9090

ignore-resolve-fail: true
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5450
  enhanced-mode: fake-ip
  default-nameserver:
  - 119.29.29.29
  - 119.28.28.28
  - 1.2.4.8
  nameserver:
  - https://dns.alidns.com/dns-query
  - https://1.1.1.1/dns-query
  - tls://dns.adguard.com:853
  - 10.10.0.21 # zju dns server
  fake-ip-filter:
  - '*.lan'
  - '*.edu.cn'
  - localhost.ptlogin2.qq.com
  - '*.*.*.*.srv.nintendo.net'
  - '*.*.*.stun.playstation.net'
  - xbox.*.microsoft.com
  - '*.*.*.xboxlive.com'

##################
### 自定义代理 ####
##################

# My UnblockNeteaseMusic on server
proxies:
- name: "UnblockNeteaseMusic"
  type: http
  server: #my server ip
  port: #port
  username:
  password:
  tls: False

####################
### 机场订阅分组 ####
####################
proxy-providers:
  IEPL+:
    type: http
    path: ./Proxies/IEPL+.yaml
    url: https://dler.cloud/subscribe/{manage_key}?protocols=ss&list=clash&match=IEPL%5C%2B
    interval: *time_update  # 订阅更新间隔（秒）
    health-check:
      enable: true
      url: *test_url
      interval: *time_test  # 测试间隔
  IEPL:
    type: http
    path: ./Proxies/IEPL.yaml
    url: https://dler.cloud/subscribe/{manage_key}?protocols=ss&list=clash&match=IEPL
    interval: *time_update  # 订阅更新间隔（秒）
    health-check:
      enable: true
      url: *test_url
      interval: *time_test  # 测试间隔

  IPLC+:
    type: http
    path: ./Proxies/IPLC+.yaml
    url: https://dler.cloud/subscribe/{manage_key}?protocols=ss&list=clash&match=IPLC%5C%2B
    interval: *time_update  # 订阅更新间隔（秒）
    health-check:
      enable: true
      url: *test_url
      interval: *time_test  # 测试间隔

  IPLC:
    type: http
    path: ./Proxies/IPLC.yaml
    url: https://dler.cloud/subscribe/{manage_key}?protocols=ss&list=clash&match=IPLC
    interval: *time_update  # 订阅更新间隔（秒）
    health-check:
      enable: true
      url: *test_url
      interval: *time_test  # 测试间隔

  BGP:
    type: http
    path: ./Proxies/BGP.yaml
    url: https://dler.cloud/subscribe/{manage_key}?protocols=ss&list=clash&match=BGP
    interval: *time_update  # 订阅更新间隔（秒）
    health-check:
      enable: true
      url: *test_url
      interval: *time_test  # 测试间隔
  
###############
### 策略组 ####
##############
proxy-groups:
- name: Proxy
  type: select
  proxies:
  - Auto - IEPL+
  - Auto - IEPL
  - Auto - IPLC+
  - Auto - IPLC
  - Auto - BGP
  - DIRECT

- name: Domestic
  type: select
  proxies:
  - DIRECT
  - Proxy

- name: Others
  type: select
  proxies:
  - Proxy
  - DIRECT
  - Domestic

- name: NeteaseMusic
  type: select
  proxies:
  - DIRECT
  - UnblockNeteaseMusic

- name: AdBlock
  type: select
  proxies:
  - REJECT
  - DIRECT
  - Proxy

- name: Apple
  type: select
  proxies:
  - DIRECT
  - Proxy

- name: AsianTV
  type: select
  proxies:
  - DIRECT
  - Domestic
  - Proxy

- name: GlobalTV
  type: select
  proxies:
  - Proxy
  - DIRECT

- name: Netflix
  type: select
  proxies:
  - Proxy
  - DIRECT

- name: Spotify
  type: select
  proxies:
  - Proxy
  - DIRECT

- name: YouTube
  type: select
  proxies:
  - Proxy
  - DIRECT

- name: Telegram
  type: select
  proxies:
  - Proxy
  - DIRECT

- name: Steam
  type: select
  proxies:
  - Proxy
  - DIRECT

- name: Speedtest
  type: select
  proxies:
  - Proxy
  - DIRECT
  - Domestic

- name: PayPal
  type: select
  proxies:
  - DIRECT
  - Proxy
  - Domestic

- name: Microsoft
  type: select
  proxies:
  - Proxy
  - DIRECT

- name: Auto - IEPL+
  type: url-test
  use:
  - IEPL+
  url: http://cp.cloudflare.com/generate_204
  interval: "3600"

- name: Auto - IEPL
  type: url-test
  use:
  - IEPL
  url: http://cp.cloudflare.com/generate_204
  interval: "3600"

- name: Auto - IPLC+
  type: url-test
  use:
  - IPLC+
  url: http://cp.cloudflare.com/generate_204
  interval: "3600"

- name: Auto - IPLC
  type: url-test
  use:
  - IPLC
  url: http://cp.cloudflare.com/generate_204
  interval: "3600"

- name: Auto - BGP
  type: url-test
  use:
  - BGP
  url: http://cp.cloudflare.com/generate_204
  interval: "3600"


#################################################################################################
### rules and rule-providers from https://github.com/lhie1/Rules/blob/master/Clash/Rule.yaml ####
#################################################################################################

rules:
- RULE-SET,Reject,AdBlock
- RULE-SET,Special,DIRECT
- RULE-SET,Netflix,Netflix
- RULE-SET,Spotify,Spotify
- RULE-SET,YouTube,YouTube
- RULE-SET,Bilibili,AsianTV
- RULE-SET,iQiyi,AsianTV
- RULE-SET,Letv,AsianTV
- RULE-SET,Netease Music,NeteaseMusic
- RULE-SET,Tencent Video,AsianTV
- RULE-SET,Youku,AsianTV
- RULE-SET,ABC,GlobalTV
- RULE-SET,Abema TV,GlobalTV
- RULE-SET,Amazon,GlobalTV
- RULE-SET,Apple News,GlobalTV
- RULE-SET,Apple TV,GlobalTV
- RULE-SET,Bahamut,GlobalTV
- RULE-SET,BBC iPlayer,GlobalTV
- RULE-SET,DAZN,GlobalTV
- RULE-SET,Disney Plus,GlobalTV
- RULE-SET,encoreTVB,GlobalTV
- RULE-SET,Fox Now,GlobalTV
- RULE-SET,Fox+,GlobalTV
- RULE-SET,HBO,GlobalTV
- RULE-SET,Hulu Japan,GlobalTV
- RULE-SET,Hulu,GlobalTV
- RULE-SET,Japonx,GlobalTV
- RULE-SET,JOOX,GlobalTV
- RULE-SET,KKBOX,GlobalTV
- RULE-SET,KKTV,GlobalTV
- RULE-SET,Line TV,GlobalTV
- RULE-SET,myTV SUPER,GlobalTV
- RULE-SET,Pandora,GlobalTV
- RULE-SET,PBS,GlobalTV
- RULE-SET,Pornhub,GlobalTV
- RULE-SET,Soundcloud,GlobalTV
- RULE-SET,ViuTV,GlobalTV
- RULE-SET,Telegram,Telegram
- RULE-SET,Steam,Steam
- RULE-SET,Speedtest,Speedtest
- RULE-SET,PayPal,PayPal
- RULE-SET,Microsoft,Microsoft
- RULE-SET,PROXY,Proxy
- RULE-SET,Domestic,Domestic
- RULE-SET,Domestic IPs,Domestic
- RULE-SET,Apple,Apple
- GEOIP,CN,Domestic
- MATCH,Others

rule-providers:
  Reject:
    type: http
    behavior: classical
    url: https://git.dler.io/lhie1/Rules/master/Clash/Provider/Reject.yaml
    path: ./Rules/Reject
    interval: *time_update_rule
  Special:
    type: http
    behavior: classical
    url: https://git.dler.io/lhie1/Rules/master/Clash/Provider/Special.yaml
    path: ./Rules/Special
    interval: *time_update_rule
  Netflix:
    type: http
    behavior: classical
    url: https://git.dler.io/lhie1/Rules/master/Clash/Provider/Media/Netflix.yaml
    path: ./Rules/Media/Netflix
    interval: *time_update_rule
  Spotify:
    type: http
    behavior: classical
    url: https://git.dler.io/lhie1/Rules/master/Clash/Provider/Media/Spotify.yaml
    path: ./Rules/Media/Spotify
    interval: *time_update_rule
  YouTube:
    type: http
    behavior: classical
    url: https://git.dler.io/lhie1/Rules/master/Clash/Provider/Media/YouTube.yaml
    path: ./Rules/Media/YouTube
    interval: *time_update_rule
  Bilibili:
    type: http
    behavior: classical
    url: https://git.dler.io/lhie1/Rules/master/Clash/Provider/Media/Bilibili.yaml
    path: ./Rules/Media/Bilibili
    interval: *time_update_rule
  iQiyi:
    type: http
    behavior: classical
    url: https://git.dler.io/lhie1/Rules/master/Clash/Provider/Media/iQiyi.yaml
    path: ./Rules/Media/iQiyi
    interval: *time_update_rule
  Letv:
    type: http
    behavior: classical
    url: https://git.dler.io/lhie1/Rules/master/Clash/Provider/Media/Letv.yaml
    path: ./Rules/Media/Letv
    interval: *time_update_rule
  Netease Music:
    type: http
    behavior: classical
    url: https://git.dler.io/lhie1/Rules/master/Clash/Provider/Media/Netease%20Music.yaml
    path: ./Rules/Media/Netease_Music
    interval: *time_update_rule
  Tencent Video:
    type: http
    behavior: classical
    url: https://git.dler.io/lhie1/Rules/master/Clash/Provider/Media/Tencent%20Video.yaml
    path: ./Rules/Media/Tencent_Video
    interval: *time_update_rule
  Youku:
    type: http
    behavior: classical
    url: https://git.dler.io/lhie1/Rules/master/Clash/Provider/Media/Youku.yaml
    path: ./Rules/Media/Youku
    interval: *time_update_rule
  ABC:
    type: http
    behavior: classical
    url: https://git.dler.io/lhie1/Rules/master/Clash/Provider/Media/ABC.yaml
    path: ./Rules/Media/ABC
    interval: *time_update_rule
  Abema TV:
    type: http
    behavior: classical
    url: https://git.dler.io/lhie1/Rules/master/Clash/Provider/Media/Abema%20TV.yaml
    path: ./Rules/Media/Abema_TV
    interval: *time_update_rule
  Amazon:
    type: http
    behavior: classical
    url: https://git.dler.io/lhie1/Rules/master/Clash/Provider/Media/Amazon.yaml
    path: ./Rules/Media/Amazon
    interval: *time_update_rule
  Apple News:
    type: http
    behavior: classical
    url: https://git.dler.io/lhie1/Rules/master/Clash/Provider/Media/Apple%20News.yaml
    path: ./Rules/Media/Apple_News
    interval: *time_update_rule
  Apple TV:
    type: http
    behavior: classical
    url: https://git.dler.io/lhie1/Rules/master/Clash/Provider/Media/Apple%20TV.yaml
    path: ./Rules/Media/Apple_TV
    interval: *time_update_rule
  Bahamut:
    type: http
    behavior: classical
    url: https://git.dler.io/lhie1/Rules/master/Clash/Provider/Media/Bahamut.yaml
    path: ./Rules/Media/Bahamut
    interval: *time_update_rule
  BBC iPlayer:
    type: http
    behavior: classical
    url: https://git.dler.io/lhie1/Rules/master/Clash/Provider/Media/BBC%20iPlayer.yaml
    path: ./Rules/Media/BBC_iPlayer
    interval: *time_update_rule
  DAZN:
    type: http
    behavior: classical
    url: https://git.dler.io/lhie1/Rules/master/Clash/Provider/Media/DAZN.yaml
    path: ./Rules/Media/DAZN
    interval: *time_update_rule
  Disney Plus:
    type: http
    behavior: classical
    url: https://git.dler.io/lhie1/Rules/master/Clash/Provider/Media/Disney%20Plus.yaml
    path: ./Rules/Media/Disney_Plus
    interval: *time_update_rule
  encoreTVB:
    type: http
    behavior: classical
    url: https://git.dler.io/lhie1/Rules/master/Clash/Provider/Media/encoreTVB.yaml
    path: ./Rules/Media/encoreTVB
    interval: *time_update_rule
  Fox Now:
    type: http
    behavior: classical
    url: https://git.dler.io/lhie1/Rules/master/Clash/Provider/Media/Fox%20Now.yaml
    path: ./Rules/Media/Fox_Now
    interval: *time_update_rule
  Fox+:
    type: http
    behavior: classical
    url: https://git.dler.io/lhie1/Rules/master/Clash/Provider/Media/Fox%2B.yaml
    path: ./Rules/Media/Fox+
    interval: *time_update_rule
  HBO:
    type: http
    behavior: classical
    url: https://git.dler.io/lhie1/Rules/master/Clash/Provider/Media/HBO.yaml
    path: ./Rules/Media/HBO
    interval: *time_update_rule
  Hulu Japan:
    type: http
    behavior: classical
    url: https://git.dler.io/lhie1/Rules/master/Clash/Provider/Media/Hulu%20Japan.yaml
    path: ./Rules/Media/Hulu_Japan
    interval: *time_update_rule
  Hulu:
    type: http
    behavior: classical
    url: https://git.dler.io/lhie1/Rules/master/Clash/Provider/Media/Hulu.yaml
    path: ./Rules/Media/Hulu
    interval: *time_update_rule
  Japonx:
    type: http
    behavior: classical
    url: https://git.dler.io/lhie1/Rules/master/Clash/Provider/Media/Japonx.yaml
    path: ./Rules/Media/Japonx
    interval: *time_update_rule
  JOOX:
    type: http
    behavior: classical
    url: https://git.dler.io/lhie1/Rules/master/Clash/Provider/Media/JOOX.yaml
    path: ./Rules/Media/JOOX
    interval: *time_update_rule
  KKBOX:
    type: http
    behavior: classical
    url: https://git.dler.io/lhie1/Rules/master/Clash/Provider/Media/KKBOX.yaml
    path: ./Rules/Media/KKBOX
    interval: *time_update_rule
  KKTV:
    type: http
    behavior: classical
    url: https://git.dler.io/lhie1/Rules/master/Clash/Provider/Media/KKTV.yaml
    path: ./Rules/Media/KKTV
    interval: *time_update_rule
  Line TV:
    type: http
    behavior: classical
    url: https://git.dler.io/lhie1/Rules/master/Clash/Provider/Media/Line%20TV.yaml
    path: ./Rules/Media/Line_TV
    interval: *time_update_rule
  myTV SUPER:
    type: http
    behavior: classical
    url: https://git.dler.io/lhie1/Rules/master/Clash/Provider/Media/myTV%20SUPER.yaml
    path: ./Rules/Media/myTV_SUPER
    interval: *time_update_rule
  Pandora:
    type: http
    behavior: classical
    url: https://git.dler.io/lhie1/Rules/master/Clash/Provider/Media/Pandora.yaml
    path: ./Rules/Media/Pandora
    interval: *time_update_rule
  PBS:
    type: http
    behavior: classical
    url: https://git.dler.io/lhie1/Rules/master/Clash/Provider/Media/PBS.yaml
    path: ./Rules/Media/PBS
    interval: *time_update_rule
  Pornhub:
    type: http
    behavior: classical
    url: https://git.dler.io/lhie1/Rules/master/Clash/Provider/Media/Pornhub.yaml
    path: ./Rules/Media/Pornhub
    interval: *time_update_rule
  Soundcloud:
    type: http
    behavior: classical
    url: https://git.dler.io/lhie1/Rules/master/Clash/Provider/Media/Soundcloud.yaml
    path: ./Rules/Media/Soundcloud
    interval: *time_update_rule
  ViuTV:
    type: http
    behavior: classical
    url: https://git.dler.io/lhie1/Rules/master/Clash/Provider/Media/ViuTV.yaml
    path: ./Rules/Media/ViuTV
    interval: *time_update_rule
  Telegram:
    type: http
    behavior: classical
    url: https://git.dler.io/lhie1/Rules/master/Clash/Provider/Telegram.yaml
    path: ./Rules/Telegram
    interval: *time_update_rule
  Steam:
    type: http
    behavior: classical
    url: https://git.dler.io/lhie1/Rules/master/Clash/Provider/Steam.yaml
    path: ./Rules/Steam
    interval: *time_update_rule
  Speedtest:
    type: http
    behavior: classical
    url: https://git.dler.io/lhie1/Rules/master/Clash/Provider/Speedtest.yaml
    path: ./Rules/Speedtest
    interval: *time_update_rule
  PayPal:
    type: http
    behavior: classical
    url: https://git.dler.io/lhie1/Rules/master/Clash/Provider/PayPal.yaml
    path: ./Rules/PayPal
    interval: *time_update_rule
  Microsoft:
    type: http
    behavior: classical
    url: https://git.dler.io/lhie1/Rules/master/Clash/Provider/Microsoft.yaml
    path: ./Rules/Microsoft
    interval: *time_update_rule
  PROXY:
    type: http
    behavior: classical
    url: https://git.dler.io/lhie1/Rules/master/Clash/Provider/Proxy.yaml
    path: ./Rules/Proxy
    interval: *time_update_rule
  Domestic:
    type: http
    behavior: classical
    url: https://git.dler.io/lhie1/Rules/master/Clash/Provider/Domestic.yaml
    path: ./Rules/Domestic
    interval: *time_update_rule
  Apple:
    type: http
    behavior: classical
    url: https://git.dler.io/lhie1/Rules/master/Clash/Provider/Apple.yaml
    path: ./Rules/Apple
    interval: *time_update_rule
  Domestic IPs:
    type: http
    behavior: ipcidr
    url: https://git.dler.io/lhie1/Rules/master/Clash/Provider/Domestic%20IPs.yaml
    path: ./Rules/Domestic_IPs
    interval: *time_update_rule
...
